#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo "Script executed from: ${PWD}"
pnpm run check-lock-files && exec git diff --cached --name-only | pnpm exec cspell --no-must-find-files --file-list stdin
